import Modal from './components/Modal/Modal';
import RegisterModal from './components/Modal/RegisterModal';
import Navbar from './components/Navbar/Navbar';
import './globals.css'
import {Nunito} from 'next/font/google';
import ToasterProvider from './providers/ToasterProvider';
import LoginModal from './components/Modal/LoginModal';
import getCurrentUser from './actions/getCurrentUser';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const font = Nunito({
  subsets: ['latin'],
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  console.log(currentUser);
  return (
    <html lang="en">
      <body className={font.className}>
        <RegisterModal />
        <LoginModal />
        <ToasterProvider />
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  )
}
